### ISSUE TITLE
distribution-type doesn't work?

### ISSUE THREAD

**Issue by ebraminio** [EdwarDDay/upgrade-gradle-action#28]
Hi, first of all, thanks for this :)

I've put 
```
        with:
           distribution-type: all
```
in my workflow https://github.com/persian-calendar/DroidPersianCalendar/commit/68808d116645edaa0b29fe29c816b15b95fccca1 but it wants me to go back to binary version again, https://github.com/persian-calendar/DroidPersianCalendar/pull/705 maybe something from my side or your side should be improved? Thanks!

**Comment by ebraminio** [comment]
Looking at the nice and simple source, I probably should've used `env:` instead `with:`, let's see how that goes. Also you apparently use https://github.com/gradle-update/update-gradle-wrapper-action in your other project however yours prints a better PR message and actually provides the option to choose the distribution, I might use that but like yours more I think, thanks :)

**Comment by EdwarDDay** [comment]
Finally found and fixed the issue while implementing a different feature:  #74. I also added a test to check, that the gradle wrapper properties file contains now the correct distribution type.
