### ISSUE TITLE
Release notes cause noise for upstream Gradle issues

### ISSUE THREAD

**Issue by Marcono1234** [EdwarDDay/upgrade-gradle-action#70]
Hello,
the feature of your GitHub action to provide `version-information`, `fixed-issues` and `known-issues` seems quite useful. However there is an issue with the current implementation: It directly links to the Gradle GitHub issues, which causes quite some 'noise' there[^1]:

![GitHub issue screenshot](https://github.com/user-attachments/assets/3cd1dc30-4421-44d0-b40e-e50b9a4942d7)

(example from https://github.com/gradle/gradle/issues/30153; it seems all of those are using your action)

GitHub's Dependabot seems to work around this by replacing the `github.com` URLs with `redirect.github.com`, for example https://redirect.github.com/fsfe/reuse-action/issues/32. The URLs still lead to the desired target, but it does not cause all these mentions for the referenced GitHub issue.
The only disadvantage is that currently GitHub shows no hover card for these links.

What do you think?

[^1]: At least this is my personal opinion on this; maybe the Gradle developers see this differently.

**Comment by EdwarDDay** [comment]
Sorry for the late reply.

That's a good point. Can I just replace it? Is there some documentation for the service? I don't want to get sued by GitHub for using their service without permission.

**Comment by Marcono1234** [comment]
I am not sure if it is officially documented, but since GitHub's Dependabot is using them, I assume the URL is stable (unless they want to risk breaking historic Dependabot pull request messages).

I am not a lawyer, but I don't think just linking to `redirect.github.com` in the release notes would cause any trouble. Users would have to visit it manually, so it won't cause any massive increase in traffic. The popular Renovate CLI seems to be using `redirect.github.com` in their messages now as well: https://github.com/renovatebot/renovate/pull/31025
But to be safe you could try contacting GitHub Support, and asking them whether linking to `redirect.github.com` is fine (maybe referring to this issue here for context).
